### ISSUE TITLE
TIM2 has 4 compare output pins ?

### ISSUE THREAD

**Issue by trimarco232** [openwch/ch32v003#10]
it looks like the capture/compare channel 1 of TIM2 is marked TIM2CH1ETR ; does this mean that  : 
- in input mode, the pin is capture input of TIM2CH1 , and ETR input of TIM2
- in output mode, the pin is compare output of TIM2CH1 ?
(important for me is output mode, because I need 8 pwm, outputs, witch was not possible with stm8s003)
thanks !

**Comment by qiyongshuang** [comment]
TIM2CH1ETR pin has two functions: 1. Input/output comparison pin function 2. External clock input pin.
![emobile_2023-02-27_11-23-10](https://user-images.githubusercontent.com/110513727/221465810-b4c080bf-0a3e-4a2b-982c-1248ba17e5a7.png)

**Comment by qiyongshuang** [comment]
TIM2CH1ETR pin has two functions: 1. Input/output comparison pin function 2. External clock input pin.
![emobile_2023-02-27_11-23-10](https://user-images.githubusercontent.com/110513727/221482957-897a04df-176d-446b-a79f-4ff667a13f19.png)
