### ISSUE TITLE
NRST option byte defaults differ from Reference Manual.

### ISSUE THREAD

**Issue by MartinEssink** [openwch/ch32v003#11]
The default value of the option bytes (See RM 16.5) seem to have the reset pin enabled by default, the value is 11010111 where bit 3 and 4 are RST_MODE (OB_RST_EN_DT1ms). In the reference manual it is stated that the default value is 11 (OB_RST_NoEN).

**Comment by qiyongshuang** [comment]
Thanks for finding the problem. RST_MODE is 10 bit (12ms) by default. We will modify it later in the manual. If you want to use PD7 as a common pin, you can set it by using WCH_LinkUility.
![微信截图_20230301163438](https://user-images.githubusercontent.com/110513727/222086557-5b25e606-34ef-4083-b6c3-d200e85c146f.png)

**Comment by MartinEssink** [comment]
Thank you for confirming this, and updating the reference manual!
