### ISSUE TITLE
licensing for hardware examples

### ISSUE THREAD

**Issue by Tonymac32** [openwch/ch32v003#12]
In the spirit of "openwch", I would recommend the CERN open hardware license https://cern-ohl.web.cern.ch/

Otherwise the designs are not truly "open"

**Comment by vazhnov** [comment]
As I see, for example, in https://github.com/openwch/ch32v003/blob/main/C%2B%2B/Use%20MRS%20Create%20C%2B%2B%20project-example/CH32V003F4P6/Core/core_riscv.c , the source code is already opensource:

> SPDX-License-Identifier: Apache-2.0

@openwch , it would be great to have an opensource license for all other files.

**Comment by vazhnov** [comment]
@qiyongshuang, did you update something in the project?
