### ISSUE TITLE
Systick Description Lacking in Datasheet

### ISSUE THREAD

**Issue by greenscreenflicker** [openwch/ch32v003#14]
Hello,
the datasheet is lacking the register description of the Systick. Can you please add a register description to the reference manual?
Thank you,
Michael

**Comment by qiyongshuang** [comment]
You will get  your need from :http://www.wch-ic.com/downloads/QingKeV2_Processor_Manual_PDF.html

**Comment by greenscreenflicker** [comment]
Thank you, that answers my question
