### ISSUE TITLE
No firmware for Micropython for this ch32v003.

### ISSUE THREAD

**Issue by anandr16910** [openwch/ch32v003#35]
Running and flashing this microcontroller board with MicroPython requires firmware associated with this part number **CH32V003**. Unfortunately, [https://micropython.org/download/] or [https://github.com/micropython/micropython?tab=readme-ov-file#supported-platforms--architectures] does not have firmware for this Microcontroller.

**Comment by mrx23dot** [comment]
micropython on 2KB RAM? :D

**Comment by anandr16910** [comment]
is it possible on 2kb ram

**Comment by martinribelotta** [comment]
> is it possible on 2kb ram

From the repo readme:

> Microcontroller targets can be as small as 256kiB flash + 16kiB RAM, although devices with at least 512kiB flash + 128kiB RAM allow a much more full-featured experience.

Maybe a old basic interpreter (with tokenization) wold be posible... but not micropython in the actual implementation
