### ISSUE TITLE
function u16 Get_ADC_Val(u8 ch) in ADC  Auto_Injection dont work

### ISSUE THREAD

**Issue by DDDD4BBB** [openwch/ch32v003#38]
In ch32v003/tree/main/EVT/EXAM/ADC/Auto_Injection/User/main.c 
function u16 Get_ADC_Val(u8 ch) (87 string) doesn't use channel selection

I use realization it function in ch32v003/tree/main/EVT/EXAM/ADC/ADC_DMA/User/main.c 
u16 Get_ADC_Val(u8 ch)
{
    u16 val;

    ADC_RegularChannelConfig(ADC1, ch, 1, ADC_SampleTime_241Cycles);
    ADC_SoftwareStartConvCmd(ADC1, ENABLE);

    while(!ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC));
    val = ADC_GetConversionValue(ADC1);

    return val;
}

**Comment by qiyongshuang** [comment]
Do you mean can’t select the number of channels? because we can choose channel .
