### ISSUE TITLE
SOP16 has broken SPI implementation (no PC5/SCK broken-out pin)

### ISSUE THREAD

**Issue by gili-yankovitch** [openwch/ch32v003#40]
I am looking at the SOP16 variation of the ch32v003. It says everywhere that it supports SPI. Although I see both the MISO and MOSI lines, the SCK pin is not broken out in this package (PC5). Has anyone used this package / know what's up with that and how one can use SPI without SCK? Both in the smaller as well as the larger datasheet it seems it is not configurable to a different port.
Help appreciated!
![image](https://github.com/openwch/ch32v003/assets/26086886/28cb77c4-74d8-43fa-bcf9-6beec136a884)
![image](https://github.com/openwch/ch32v003/assets/26086886/41888779-f2ab-4a49-b9e4-57b96ab72e34)

**Comment by trimarco232** [comment]
you are unfortunately right ,  no SCK = no SPI
it is a shame , but it is advertised so
you have to do SPI manually , or chose another MCU
the only thing one could do with MOSI pin is to generate one wire command signal , like WS2811 (but not sure as never tried it)
