### ISSUE TITLE
What is the "recognition mode" of RISC-V

### ISSUE THREAD

**Issue by luansh** [openwch/ch32v003#51]
in startup_ch32v00x.S
  ......
/* Configure the interrupt vector table recognition mode and entry address mode */
    la t0, _start
    ori t0, t0, 3
    csrw mtvec, t0

in risc-v's spec, there are only direct mode(0b00) and vectored mode(0b01) in mtvec, 0b10 and 0b11 are reserved
so what is recognition mode?
tks

**Comment by qiyongshuang** [comment]
![image](https://github.com/user-attachments/assets/053d1b71-b186-42f3-af5d-8f66fb5425bc)

**Comment by qiyongshuang** [comment]
https://www.wch-ic.com/downloads/QingKeV2_Processor_Manual_PDF.html
