### ISSUE TITLE
Moun River Studio "Peripherals" view empty

### ISSUE THREAD

**Issue by uliano** [openwch/ch32v003#8]
Moun River Studio "Peripherals" view is empty when I open one of the examples of this repository. 

On the contrary if I create a new project I can see/edit all the peripheral's registers.

How can I fix this for the projects in the EVT/EXAM directory?

**Comment by qiyongshuang** [comment]
Click the triangle arrow next to the debug button on the toolbar,choise " Debug Configuration".Click"SVD Path",Fill in the .svd file path corresponding to the current project. you can create a new project ,then copy/paste the file path .
![emobile_2023-02-22_10-32-37](https://user-images.githubusercontent.com/110513727/220507152-0adfe824-6bb3-448e-99bd-e6dde639d21f.png)
![emobile_2023-02-22_10-33-35](https://user-images.githubusercontent.com/110513727/220507151-90b13d44-aa8a-48dd-81a5-9f85aaa58730.png)

**Comment by uliano** [comment]
Thank you, this solved my question.
