### ISSUE TITLE
Example for I2C is not working

### ISSUE THREAD

**Issue by waiweng83** [openwch/ch32v003#9]
The I2C example is not working. The Master always hold the SCL pin low.
I've added external 4K7 pull up resistor to both PC1 and PC2 but it's still the same.

**Comment by qiyongshuang** [comment]
I want to know which EVT does not work or all I2C routines do not work.

**Comment by waiweng83** [comment]
> I want to know which EVT does not work or all I2C routines do not work.

I tried "I2C_7bit_Mode" and it's not working. Didn't try on other examples.

**Comment by qiyongshuang** [comment]
In "I2C_7bit_Mode“, first reset the slave board, then reset the host board.  "I2C_7bit_Mode“rountine sends and receives multiple arrays, and the result printing will have a delay.
![emobile_2023-02-27_15-10-05](https://user-images.githubusercontent.com/110513727/221497867-7e89b13c-7a3e-4c88-ae64-5a1e2c91f921.png)
